title = "Xintong Jiang"
baseURL = "https://jiangzncu.github.io"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Zhejiang, CN"
email = "jiangzncu@gmail.com"
favicon = "/favicon.ico"
firstName = "Xintong"
lastName = "Jiang"
phone = ""
profileImage = "img/selfie.jpg"
showQr = false
showContact = false
showBoards  = false
showCertifications = false
showSocializations = false
sections = ["publications","experience","education"]
vcardfields = [
    "name",
    "image",
    "org",
    "email",
    "workemail",
    "phone",
    "url",
    "title"
]

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

# [[params.handles]]
#     name = "LinkedIn"
#     link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/jiangzncu/"

# [[params.handles]]
#     name = "Keybase"
#     link = "https://keybase.io/edwardawebb"
#     icon = "keybase"
    
# [[params.handles]]
#     name = "Bluesky"
#     link = "https://bsky.app/profile/webbinaro.dev"
#     icon = "bluesky"

# [[params.handles]]
#     link = "https://stackoverflow.com/users/82880/eddie"
#     name = "Stack Overflow"
#     icon = "stack-overflow"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"


[mediaTypes]
  [mediaTypes."text/vcard"]
    suffixes = ["vcf"]

[outputFormats]
  [outputFormats.VCard]
    mediaType = "text/vcard"
    baseName = "contact"
    isPlainText = true
    notAlternative = true